language: cpp
compiler:
- clang
os:
- linux
- windows
before_install:
  - sudo apt-get update
script:
  - mkdir build
  - cd build
  - cmake -DEDITOR=0 -USE_KIOSLAVE=0 -DUSE_QBLP=0 -DUSE_OGREBLP=0 -DCMAKE_BUILD_TYPE=Debug .. && make && cpack .
addons:
  apt:
    sources:
      - boost-latest
     # - debian-sid
    packages:
      - cmake
      - libboost1.55-all-dev
     # - qt5-default