language: cpp
compiler:
  - gcc
  - clang
os:
  - linux

script:
  - mkdir build
  - cd build
  - cmake -DEDITOR=0 -USE_KIOSLAVE=0 -DUSE_QBLP=0 -DUSE_OGREBLP=0 -DCMAKE_BUILD_TYPE=Debug .. && make && cpack .
addons:
  apt:
    sources:
      - boost-latest
      - kalakris-cmake
     # - debian-sid
    packages:
      - cmake
      - libboost1.55-all-dev
     # - qt5-default