language: cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    sources:
      - boost-latest
      - george-edison55-precise-backports
    packages:
      - cmake-data
      - cmake
      - valgrind
      - libboost-all-dev
      - libbz2-dev
      - gettext

script:
     - mkdir -p build
     - cd build
     - cmake -DEDITOR=0 -DUSE_KIOSLAVE=0 -DUSE_QBLP=0 -DUSE_OGREBLP=0 -DUSE_MIME=0 -DCMAKE_BUILD_TYPE=Debug ../
     - make
     - cpack .
     - ctest -T Test
     - ctest -T Coverage
