language: cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    sources:
      - boost-latest
      - george-edison55-precise-backports
    packages:
      - cmake-data
      - cmake
      - valgrind
      - libboost-all-dev
      - libbz2-dev
      - gettext

script:
     - mkdir -p build
     - cd build
     - cmake -DEDITOR=OFF -DUSE_KIOSLAVE=OFF -DUSE_QBLP=OFF -DUSE_OGREBLP=OFF -DUSE_MIME=OFF -DCMAKE_BUILD_TYPE=Debug ../
     - make
     - cpack .
     - ctest -T Test
