language: cpp
compiler:
- clang
os:
- linux
- windows
before_install:
  - sudo apt-get update
script:
  - mkdir build
  - cd build
  - cmake .. && make && cpack .
addons:
  apt:
    sources:
      - boost-latest
      - debian-sid
    packages:
      - cmake
      - libboost1.55-all-dev
      - qt5-default