language: cpp
compiler:
- clang
os:
- linux
- windows
script:
  - mkdir build
  - cd build
  - cmake .. && make && cpack .
addons:
  apt:
    packages:
      - cmake
      - boost-defaults
      - qt5-default