version: '{build}'
branches:
  only:
  - master
clone_folder: c:\projects\wc3lib
image:
- Visual Studio 2017
configuration:
- Release
- Debug
platform:
- x64
environment:
  matrix:
  - arch: Win64
  # - arch: #does not work, Release|x64 not a valid target
matrix:
  fast_finish: true

install:
  - nuget install libjpeg
  - nuget install bzip2
  - nuget install boost
  
# skip unsupported combinations
init:
- set arch=
- if "%arch%"=="Win64" ( set arch= Win64)
- echo %arch%
- echo %APPVEYOR_BUILD_WORKER_IMAGE%
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
- echo %generator%

before_build:
- cmd: |-
    mkdir build
    cd build
    cmake --version
    cmake .. -G %generator% -DMDLX=0 -DUSE_KIOSLAVE=0 -DUSE_OGREBLP=0
build:
  project: c:\projects\wc3lib\build\template.sln
  verbosity: minimal
  parallel: true
# scripts to run after build
after_build:
  - cd c:\projects\wc3lib\build
  - cpack -G NSIS .
only_commits:
  files:
    - CMakeLists.txt
    - appveyor.yml
    - source/
    - cmake/
