version: '{build}'
branches:
  only:
  - master
clone_folder: c:\projects\wc3lib
image:
- Visual Studio 2017
configuration:
- Release
- Debug
platform:
- x64
environment:
  matrix:
  - arch: Win64
matrix:
  fast_finish: true

install:
  - nuget install libjpeg -Version 9.2.0.1
  - nuget install bzip2
  - nuget install boost -Version 1.66.0
  - nuget install boost-vc141 -Version 1.66.0
  
# skip unsupported combinations
init:
- set arch=
- if "%arch%"=="Win64" ( set arch= Win64)
- echo %arch%
- echo %APPVEYOR_BUILD_WORKER_IMAGE%
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
- echo %generator%

before_build:
- cmd: |-
    dir /ad /b /s
    dir /a-d /b /s
    mkdir build
    cd build
    cmake --version
    cmake .. -G %generator% -DMDLX=0 -DUSE_KIOSLAVE=0 -DUSE_OGREBLP=0 -DJPEG_INCLUDE_DIR="C:\projects\wc3lib\libjpeg.9.2.0.1\build\native\include" -DJPEG_LIBRARY="C:\projects\wc3lib\libjpeg.9.2.0.1\build\native\lib\v120\x64\Debug\dynamic" -DBZIP2_INCLUDE_DIR="C:\projects\wc3lib\bzip2.1.0.6.11\build\native\include" -DBZIP2_LIBRARIES="C:\projects\wc3lib\bzip2.1.0.6.11\build\native\lib\v100\x64\Debug\dynamic\stdcall\libbz2.lib" -DBOOST_ROOT="C:\projects\wc3lib\boost.1.66.0.0" -DBOOST_INCLUDEDIR="C:\projects\wc3lib\boost.1.66.0.0\lib\native\include" -DBOOST_LIBRARYDIR=""
build:
  project: c:\projects\wc3lib\build\template.sln
  verbosity: minimal
  parallel: true
# scripts to run after build
after_build:
  - cd c:\projects\wc3lib\build
  - cpack -G NSIS .
only_commits:
  files:
    - CMakeLists.txt
    - appveyor.yml
    - source/
    - cmake/
